### ISSUE TITLE
Resnet 101 features

### ISSUE THREAD

**Issue by aurooj** [jayleicn/TVQA#10]
Hi, in your paper, section **4.1. Video Features**, you mentioned as follows:

> We also use ResNet101 (He et al., 2016) trained on ImageNet (Deng et al., 2009) to extract whole image features.

Does it mean that video frames were resized to 224x224 for feature extraction rather than using center crop?

**Comment by jayleicn** [comment]
“whole image” here actually means this is not a region-level feature, but an image level feature. But yes, I resized to 224x224 rather than using center crop. It might be better to use center crop instead, not sure.

**Comment by aurooj** [comment]
I see. Thanks for your reply. I will try both of them.
