### ISSUE TITLE
Frame index alignment?

### ISSUE THREAD

**Issue by Jumperkables** [jayleicn/TVQA#15]
The frames in downloaded in your dataset are indexed in their folders starting 1, (00001.jpg)
When using timestamps your indexing of course starts from 0
Your tvqa_dataset object loads visual concepts as so:

> cur_vis_sen = self.vcpt_dict[cur_vid_name][cur_start:cur_end + 1]

Your imagenet video features are loaded as so:

> cur_vid_feat = torch.from_numpy(self.vid_h5[cur_vid_name][cur_start:cur_end])
cur_vis_sen has length 31
cur_vid_feat has length 30

Can you please clarify, with an example, exactly what indexing should be used?
Thanks,
Jumperkables

**Comment by Jumperkables** [comment]
Additionally, when your dataset was prepared. Does the image 00001.jpg correspond to the first element and 0th index of all your features?

I have found there are examples where cur_start = 0, implying the first frame is the 0th index. Am i correct to assume that: 
cur_start = 0 
cur_end = 5
should involve 00001.jpg , ..... , 00006.jpg?
(Edit to add extra question)

**Comment by jayleicn** [comment]
Hi @Jumperkables ,

Yes, the features (for all different kinds of features) and the frames are always in the same order. E.g., the first (indexed 0 in Python) ImageNet feature for any video corresponds to the first (00001.jpg) image of the video.

Both `[cur_start:cur_end + 1]` and `[cur_start:cur_end]` should be fine to use, as the`cur_start`, `cur_end` are not accurate by themselves. But I did make a mistake writing the code, I meant to use the former. Have a look at this function will give you more details: https://github.com/jayleicn/TVQA/blob/master/preprocessing.py#L128.

Best,
Jie

**Comment by Jumperkables** [comment]
Thanks for clarification!
cheers
