### ISSUE TITLE
data in download.sh not found

### ISSUE THREAD

**Issue by lixiangpengcs** [jayleicn/TVQA#2]
In download.sh, there are 404 errors in these two data: 

wget http://tvqa.cs.unc.edu/files/frm_cnt_cache.tar.gz -q --show-progress
wget http://tvqa.cs.unc.edu/files/tvqa_data.md5 -q --show-progress

I hope it can be updated.

**Comment by jayleicn** [comment]
Hi @lixiangpengcs,

It works now. Thanks for letting me know!

Jie

**Comment by staceycy** [comment]
Hi @jayleicn ,

Thank you for your efforts.

I got some problem when running the download.sh and the output is as follows:
>md5sum: det_visual_concepts.pickle.tar.gz: No such file or directory
>det_visual_concepts.pickle.tar.gz: FAILED open or read
>md5sum: WARNING: 1 listed file could not be read
>[Log] Found corrupted file, please re-download the files.

Then I download the det_visual_concepts.pickle.tar.gz, it gives:
>det_visual_concepts.pickle.tar.gz: FAILED
>md5sum: WARNING: 1 computed checksum did NOT match
>[Log] Found corrupted file, please re-download the files.

It seems I download the wrong file. 
Could you please help to check?

Thank you.
Stacey

**Comment by jayleicn** [comment]
Hi @staceycy,

I corrected the file and its md5sum, it should be working now. 

Jie

**Comment by staceycy** [comment]
Hi @jayleicn ,

Thank you for your quick response. 
It works now. 

Stacey

**Comment by wangjinjie722** [comment]
Hi @jayleicn ,
It seems that the same things happened again:
```
md5sum: det_visual_concepts.pickle.tar.gz: No such file or directory
det_visual_concepts.pickle.tar.gz: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
[Log] Found corrupted file, please re-download the files.
```
Could you please help to fix it? Thanks in advance.

**Comment by jayleicn** [comment]
Hi @wangjinjie722, It has been fixed. Thanks!!!

**Comment by wangjinjie722** [comment]
> Hi @wangjinjie722, It has been fixed. Thanks!!!

It still not works.
```
md5sum: ' det_visual_concepts_hq.pickle.tar.gz': No such file or directory
 det_visual_concepts_hq.pickle.tar.gz: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
[Log] Found corrupted file, please re-download the files.
```

**Comment by jayleicn** [comment]
Sorry I put an extra space in the `tvqa_data.md5` file, it should be working now.

**Comment by wangjinjie722** [comment]
> Sorry I put an extra space in the `tvqa_data.md5` file, it should be working now.

Thank you for the help! :-)
