### ISSUE TITLE
the file tvqa_qa_release.tar.gz cannot be download

### ISSUE THREAD

**Issue by DoubtedSteam** [jayleicn/TVQA#20]
the url for file tvqa_qa_release.tar.gz cannot be opened
would you mind sharing this file?

**Comment by jayleicn** [comment]
Thanks for letting me know! Our web server is down due to a hardware failure, we are working on a fix but we don't have an ETA yet. I'll keep you posted. -- Jie

**Comment by jayleicn** [comment]
The data is now back in [this new link](https://nlp.cs.unc.edu/data/jielei/tvqa/tvqa_public_html/).

Best,
Jie
