### ISSUE TITLE
length for each video

### ISSUE THREAD

**Issue by xiaocaijiayou** [jayleicn/TVQA#3]
Thank you for sharing the dataset and code.

Could you please include the length of each video in the dataset?

Thank you!

**Comment by jayleicn** [comment]
Hi,  

I have released the frame count for each video, which could be used to approximately calculate the length of the videos (divide the count by 3, since the frames are extracted at 3 FPS). Does this meet your needs?

You can download the file here:
http://tvqa.cs.unc.edu/files/frm_cnt_cache.tar.gz

Jie

**Comment by xiaocaijiayou** [comment]
Thank you very much!

**Comment by aurooj** [comment]
@jayleicn I checked, the maximum length of videos in the file you provide is 818 frames meaning 272/273 frames for the maximum length video. Whereas in the dataset, I can see the video clips with lengths exceeding maximum length at 3 FPS. 
Does it mean that the frames provided aren't already at 3 FPS? I am confused.

**Comment by jayleicn** [comment]
That's strange, the frames are already 3 FPS. How many such cases are there? And what are their lengths?

**Comment by aurooj** [comment]
Thanks for the prompt response. Let me pull this information and share with you.

**Comment by aurooj** [comment]
Just in the folder for grey_frames, it has 665 such video clips. Attached are the names with the frames count. 

Does it mean that we don't have to divide the lengths by 3 in the file you  provided? How did you handle such long videos in your code then?
[clips_with_frames_count.txt](https://github.com/jayleicn/TVQA/files/2805764/clips_with_frames_count.txt)

**Comment by jayleicn** [comment]
Hi @aurooj ,

We may have some misunderstanding here. The frames are extracted at 3FPS, so for a 90 secs long video, we will have ~270 frames. The numbers in the file I provided are number_frames (as the filename frm_cnt_cache.tar.gz suggests) rather than video length (secs).

**Comment by aurooj** [comment]
> Hi,
> 
> I have released the frame count for each video, which could be used to approximately calculate the length of the videos (divide the count by 3, since the frames are extracted at 3 FPS). Does this meet your needs?
> 
> You can download the file here:
> http://tvqa.cs.unc.edu/files/frm_cnt_cache.tar.gz
> 
> Jie

Oh okay. This means the frame count need to be multiplied by 3, to get the actual video length, right?

**Comment by jayleicn** [comment]
Nope, that means they need to be divided by 3 to get the video lengths.

**Comment by aurooj** [comment]
I see. Yes, that clearly was a misunderstanding then. This meant the longest video had actual length of 818/3 ~= 273 seconds(4.55 minutes).

Thanks for the clarification.
