### ISSUE TITLE
Some errors occur while dealing with imagenet feature

### ISSUE THREAD

**Issue by lixiangpengcs** [jayleicn/TVQA#4]
My environment is pytorch=0.4.0 and python=2.7.12 and the code runs well while dealing with subtitle data and visual concept data. But I meet some errors while dealing with imagenet feature. I download the latest feature file: tvqa_imagenet_pool5_hq.h5 from google drive and modify "vid_feature_path" in the config.py. 

The error information is : 

Loading cache ...
activate video stream
0it [00:00, ?it/s]Traceback (most recent call last):
  File "main.py", line 128, in <module>
    cur_acc = train(opt, dset, model, criterion, optimizer, epoch, best_acc)
  File "main.py", line 47, in train
    valid_acc, valid_loss = validate(opt, dset, model, mode="valid")
  File "main.py", line 84, in validate
    for _, batch in enumerate(valid_loader):
  File "/home/user/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/user/TVQA/tvqa_dataset.py", line 111, in __getitem__
    cur_vid_feat = nn.functional.normalize(cur_vid_feat, p=2, dim=1)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/functional.py", line 2023, in normalize
    return input / input.norm(p, dim, True).clamp(min=eps).expand_as(input)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method tqdm.__del__ of 0it [01:03, ?it/s]> ignored

I don't know what caused this error. I will appreciate it if you can give me some help.

**Comment by HYPJUDY** [comment]
Same error. Haven't solved.

**Comment by lixiangpengcs** [comment]
I have solved this problem.

**Comment by HYPJUDY** [comment]
@lixiangpengcs Can you tell us how to solve this problem? Thanks!

**Comment by noagarcia** [comment]
I am facing the same problem. Can you explain how you solve it please? @lixiangpengcs

**Comment by lixiangpengcs** [comment]
> @lixiangpengcs Can you tell us how to solve this problem? Thanks!

Sorry for the delay. There is a problem with the features provided by the author. Given frame index is out of  frame feature scope. You can expand frame feature by your own.

**Comment by lixiangpengcs** [comment]
> I am facing the same problem. Can you explain how you solve it please? @lixiangpengcs
Sorry for the delay. There is a problem with the features provided by the author. Given frame index is out of frame feature scope. You can expand frame feature by your own.
