### ISSUE TITLE
why always occupy GPU 0 for ~600MB memory when I let device =1?

### ISSUE THREAD

**Issue by orchardchang** [jayleicn/TVQA#6]
Hi, I have a problem about using GPU.
When I let device =1 in config.py, the program always occupies GPU 0 for ~600MB memory.
I want to know how to solve the problems. Thanks.

**Comment by jayleicn** [comment]
Not sure what's happening. If you want to only use GPU 1, the best way to do so is:
`export CUDA_VISIBLE_DEVICES=1`

**Comment by orchardchang** [comment]
Hi @jayleicn ,  `export CUDA_VISIBLE_DEVICES=1` still not works. 
But I think it is probably a bug of Pytorch.

**Comment by jayleicn** [comment]
After setting export CUDA_VISIBLE_DEVICES=1, you need to set device 0.

**Comment by orchardchang** [comment]
> After setting export CUDA_VISIBLE_DEVICES=1, you need to set device 0.

It works. Thanks for your hlep.
