### ISSUE TITLE
How to Training My Own model?

### ISSUE THREAD

**Issue by Ign0reLee** [jayleicn/TVQA#8]
Hi, I was interested in your model, 

So I turned it around, and I succeeded in running the pre-train model.

And I saw a paper and got a question.

I want to learn from my own image and title, but I do not seem to have guidelines for my own model.

Do you have any tips or guidelines for learning your own model?

thanks for reading

**Comment by jayleicn** [comment]
Hi @Ign0reLee ,

Just to clarify, there is no pre-trained model in this repo, so you have already succeeded in training the model, but with TVQA data. To train on your own data, prepare your data in the same input format required by the model.

Best,
Jie

**Comment by Ign0reLee** [comment]
thanks for replying

I checked that, It works well now

thank you
